name: Pull Request validation

on: [pull_request]


jobs:
  2-logicsig-contracts-ci:
    name: Run 2-logicsig-contracts validation
    uses: ./.github/workflows/2-logicsig-contracts-ci.yaml

  2-logicsig-frontend-ci:
    name: Run 2-logicsig-frontend validation
    uses: ./.github/workflows/2-logicsig-frontend-ci.yaml

